040 login system
johnmcg04/FlashFeetAPI pull request #12
Opened 2024-01-10 09:44 UTC by johnmcg04

This PR references ticket US040-login-system

This ticket states it needs to be able to:
- decrypt salted and hash passwords
- If user and password match database record, generate a JWT token and return to the UI
- UI should JWT token in cookie

**Here is a screenshot of the swagger working for this PR:**
![Screenshot 2024-01-10 at 09 29 47](https://github.com/johnmcg04/FlashFeetAPI/assets/145208852/51d7f3a8-b6c9-4446-946e-256767dd6626)
<Br>

</Br>
**Here is a screenshot of the salted and hashed passwords in the database:**
<img width="576" alt="Screenshot 2024-01-10 at 09 44 11" src="https://github.com/johnmcg04/FlashFeetAPI/assets/145208852/9b2b6acf-df29-4334-8ffb-a966beaa4901">

<Br>

</Br>

**_Here is a screenshot of the tests passing:_**

**Integration tests:**
![Screenshot 2024-01-10 at 09 22 37](https://github.com/johnmcg04/FlashFeetAPI/assets/145208852/90e636ad-cccc-4088-a05e-9ae8acf65eb7)

<Br>

</Br>
**Unit tests:**
![Screenshot 2024-01-10 at 09 35 59](https://github.com/johnmcg04/FlashFeetAPI/assets/145208852/344b5db1-ed7a-41a6-b344-dd2306b00f11)

This screenshot is not previewing for me however if you type in the URL you can see the screenshot:
https://github.com/johnmcg04/FlashFeetAPI/assets/145208852/344b5db1-ed7a-41a6-b344-dd2306b00f11

<Br>

</Br>

### Checklist

- [ ] **Code Quality:**
  - [✅] Code follows the project's coding standards.
  - [✅] Code is well-documented, including inline comments where necessary.
  - [✅] No unnecessary or commented-out code.

- [ ] **Testing:**
  - [✅] Unit tests have been added or updated to cover the changes.
  - [✅] Integration tests (if applicable) have been added or updated.
  - [✅] Manual testing has been performed and relevant scenarios tested.

2024-01-10 12:26 UTC, TaylorJCrawford commented on FlashFeetAPI/dependency-reduced-pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file shouldn't be committed.

2024-01-10 12:26 UTC, TaylorJCrawford commented on FlashFeetAPI/src/main/java/org/example/db/AuthDao.java
> +        String token = UUID.randomUUID().toString();
As per the ticket requirements we are expecting to use a JWT here. Not UUID. This will have to be highlight to the customer.

2024-01-10 12:26 UTC, TaylorJCrawford commented on FlashFeetAPI/src/main/java/org/example/db/DatabaseConnector.java
> +        try (FileInputStream propsStream = new FileInputStream("db.properties")){
Would be best to use Environment Variables -> As you will need this for your AWS deployments.

2024-01-10 12:26 UTC, TaylorJCrawford commented on FlashFeetAPI/src/main/java/org/example/resources/AuthController.java
> +            return Response.status(Response.Status.BAD_REQUEST).entity(e.getMessage()).build();
This should be an "Internal Server Error" 500

2024-01-10 12:26 UTC, TaylorJCrawford commented on FlashFeetAPI/src/main/java/org/example/resources/AuthController.java
> +            return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(e.getMessage()).build();
This should be a 401 (Unauthorized).

2024-01-10 12:26 UTC, TaylorJCrawford commented on FlashFeetAPI/src/main/java/org/example/resources/AuthController.java
> +            throw new RuntimeException(e);
Its not the best idea to throw an exception here. Would be better practice to return an error response. Possibly a 500 internal server error.

2024-01-10 12:26 UTC, TaylorJCrawford commented on FlashFeetAPI/src/main/resources/password4j.properties
> +#resistant to GPU/ASIC attacks, TMTO attacks and side channel attacks
Is this still being used?

2024-01-10 13:37 UTC, johnmcg04 commented on FlashFeetAPI/src/main/java/org/example/db/AuthDao.java
> +        String token = UUID.randomUUID().toString();
👍

2024-01-10 14:30 UTC, johnmcg04 commented on FlashFeetAPI/src/main/java/org/example/db/DatabaseConnector.java
> +        try (FileInputStream propsStream = new FileInputStream("db.properties")){
Environmental variables done 👍

2024-01-10 14:45 UTC, johnmcg04 commented on FlashFeetAPI/src/main/java/org/example/db/DatabaseConnector.java
> +        try (FileInputStream propsStream = new FileInputStream("db.properties")){
Changed the database connector class to enable them

2024-01-10 15:56 UTC, johnmcg04 commented
Dodgy linter not picking up a file that isn't there 🙃

2024-01-10 16:15 UTC, shaunganley requested changes

2024-01-10 16:15 UTC, shaunganley commented on FlashFeetAPI/src/main/java/org/example/api/AuthService.java
> +    }
```suggestion
    private AuthDao authDao;
    Connection c;

    public AuthService(AuthDao authDao, DatabaseConnector databaseConnector) throws DatabaseConnectionException, SQLException {
this.authDao = authDao;
this.c = databaseConnector.getConnection();
    }
```

2024-01-10 16:15 UTC, shaunganley commented on FlashFeetAPI/src/main/java/org/example/api/AuthService.java
> +    }
you're not setting the parameters being passed in to your constructor so you wouldn't be able to mock them out in tests

2024-01-10 16:15 UTC, shaunganley commented on FlashFeetAPI/src/main/java/org/example/resources/JobRoleController.java
> +            throw new RuntimeException(e);
```suggestion
        } catch (FailedToGetJobsException | SQLException | DatabaseConnectionException e){
            System.err.println(e.getMessage());

            return Response.serverError().build();
        }
```

2024-01-10 16:15 UTC, shaunganley commented on FlashFeetAPI/src/main/java/org/example/resources/JobRoleController.java
> +            throw new RuntimeException(e);
runtime exception is generic, you should return a response so you have control over what gets returned to user

2024-01-10 16:15 UTC, shaunganley commented on FlashFeetAPI/src/main/java/org/example/trueApplication.java
> +        }
this shouldn't be needed, the AuthController should catch the DatabaseConnectionException rather than throwing it

2024-01-10 16:15 UTC, shaunganley commented on FlashFeetAPI/src/test/java/org/example/api/integration/AuthIntegrationTest.java
> +    public void authLogin_ShouldAllowLogin_WhenValidLoginDetailsEntered() {
these tests are more like unit tests. you should have 2 integration tests. 1 with valid login (use environment variables, don't harcode valid credentials even in tests) that expects a token to be returned, and 1 with invalid credentials that expects a 500 to be returned

2024-01-10 16:15 UTC, shaunganley commented on FlashFeetAPI/src/test/java/org/example/api/integration/AuthIntegrationTest.java
> +public class AuthIntegrationTest {
missing integration tests for isadmin endpoint

2024-01-10 16:15 UTC, shaunganley commented on FlashFeetAPI/src/test/java/org/example/api/service/AuthServiceTests.java
> +}
these tests aren't testing anything as you hadn't mocked out the dao and connector in the constructor correctly. once thats fixed make sure your testing each possible outcome int he code

2024-01-10 16:15 UTC, shaunganley commented on FlashFeetAPI/src/test/java/org/example/api/service/JobRoleServiceTests.java
> +        void getAllJobRoles_shouldReturnAllJobRoles_whenDaoReturnsAllJobRoles() throws SQLException, DatabaseConnectionException, JobRoleDoesNotExistException, FailedToGetJobsException {
should have unit tests for exception scenarios as well but I understand that this isn't the code for this feature

2024-01-11 13:58 UTC, Breanna-loughrey approved these changes

2024-01-11 14:09 UTC, merged