US020 - Delete a role
johnmcg04/FlashFeetAPI pull request #8
Opened 2023-12-14 12:10 UTC by Breanna-loughrey

<img width="393" alt="Screenshot 2023-12-14 at 12 03 31" src="https://github.com/johnmcg04/FlashFeetAPI/assets/145446184/db12fb08-96dc-4e08-838d-ff595f646e61">

- Added delete-job-role endpoint and deleteJobRole in JobRoleService and JobRoleDao, as well as getJobRole.

<img width="1084" alt="Screenshot 2023-12-14 at 12 08 32" src="https://github.com/johnmcg04/FlashFeetAPI/assets/145446184/956531e9-4ce2-4b96-a1d3-128322daa0c9">

2023-12-14 13:55 UTC, lullabelle requested changes
Hi
We need a member of the team to review before Josh or I can!

2023-12-14 14:01 UTC, autumncraig approved these changes

2023-12-15 14:29 UTC, jkelso662 requested changes
I think there are a few things to do with constructors in this but other than that - looking good! Nearly there :) Again I'm seeing these gitignore files eta in so many of your teams PRs! Can't wait to get them merged haha

2023-12-15 14:29 UTC, jkelso662 commented on FlashFeetAPI/src/main/java/org/example/api/JobRoleService.java
> +    }
Is there a reason you need these empty constructors? Especially the second one that ignores the two parameters?

2023-12-15 14:29 UTC, jkelso662 commented on FlashFeetAPI/src/main/java/org/example/cli/JobRole.java
> +    private String jobRole;
When we create a job role, should we not use the constructor to pass in the parameters and set them?

2023-12-15 14:29 UTC, jkelso662 commented on FlashFeetAPI/src/main/java/org/example/trueApplication.java
> +        // TODO: application initialization
Can probably remove this as you have already implemented

2023-12-18 15:45 UTC, jkelso662 requested changes
Couple of small things to fix but nearly there! Great PR title and description - I'd love to see the other PR titles match this format.

2023-12-18 15:45 UTC, jkelso662 commented on FlashFeetAPI/src/main/java/org/example/exception/DatabaseConnectionException.java
Does this need implimented?

2023-12-18 15:45 UTC, jkelso662 commented on FlashFeetAPI/src/test/java/org/example/api/service/JobRoleServiceTests.java
> +
Watch out for all this blank space! haha Take pride in making your classes neat and tidy 😄

2023-12-18 15:45 UTC, jkelso662 commented on FlashFeetAPI/src/main/java/org/example/db/JobRoleDao.java
> +        // Connection c = databaseConnector.getConnection();
🚨

2023-12-18 15:45 UTC, jkelso662 commented on FlashFeetAPI/.gitignore
I've seen this file sooo many times! hahaha

2023-12-18 15:45 UTC, jkelso662 commented on .idea/FlashFeetAPI.iml
These files will need removed from your repo as they should be ignored now by your gitignore file

2023-12-22 14:41 UTC, lullabelle commented
your checks are still failing here but we would love to get this reviewed for you before we go? Can you fix?

2023-12-22 14:54 UTC, CDawson8 commented
That is the workflow fixed so all checks are now passing. Forgot I would need to fix the workflow file on each individual branch, but should be passing the checks now.

2024-01-10 14:38 UTC, closed without merging