Us001 view job roles
johnmcg04/FlashFeetAPI pull request #9
Opened 2023-12-14 22:40 UTC by johnmcg23

This PR references ticket US001, this user story states: 

_As a Kainos employee
I want to view job roles within Kainos 
So that I can see all the job roles available in Kainos_

In this PR I have written a test to test the getAllJobRoles() method in the jobRoleService class, mocking the JobRoleDAO class:
<img width="1044" alt="Screenshot 2023-12-14 at 22 09 04" src="https://github.com/johnmcg04/FlashFeetAPI/assets/147390964/57cfebee-0299-4fdb-8ba1-7ec6dac55e3b">
_
_
_

I have also hit the /job-role-list endpoint to ensure it works, this returned a 200 code indicating everything was 👍:
<img width="1402" alt="Screenshot 2023-12-14 at 22 27 16" src="https://github.com/johnmcg04/FlashFeetAPI/assets/147390964/9bb4d22f-0df3-4820-ac43-3f5797162047">

_
_
_
**Code changes**: 🔴**_This will have to be carried through into the other tickets_** 🔴
In this PR I have changed around parameters for the getAllJobRoles() method, this was due to being able to test the JobService class.

2023-12-15 09:28 UTC, autumncraig approved these changes

2023-12-15 14:19 UTC, jkelso662 requested changes
Not bad! Glad you have some tests in there 💯  however there is some commented code in there that can't be allowed in. Remember to review your own PR before assigning to me and Joanne. Also I assume there is still a bunch of stuff to go into Pre-Production because I feel like I've seen your gitignore file added like 4 times now 😆

2023-12-15 14:19 UTC, jkelso662 commented on FlashFeetAPI/src/main/java/org/example/db/JobRoleDao.java
> +        // Connection c = databaseConnector.getConnection();
Commented out code shouldn't be commited!

2023-12-15 14:19 UTC, jkelso662 commented on FlashFeetAPI/src/main/java/org/example/exception/DatabaseConnectionException.java
> +public class DatabaseConnectionException extends Throwable {
Should this not be implimented?

2023-12-15 14:19 UTC, jkelso662 commented on FlashFeetAPI/src/main/java/org/example/exception/JobRoleLengthException.java
> +public class JobRoleLengthException extends Throwable {
This also needs implemented

2023-12-15 14:19 UTC, jkelso662 commented on FlashFeetAPI/src/test/java/org/example/api/service/JobRoleServiceTests.java
> +//}
😬

2023-12-15 14:19 UTC, jkelso662 commented on FlashFeetAPI/src/main/java/org/example/trueApplication.java
> +        // TODO: implement application
Probably don't need this anymore

2023-12-15 14:19 UTC, jkelso662 commented on FlashFeetAPI/src/main/java/org/example/trueApplication.java
> +        // TODO: application initialization
Or this

2023-12-15 15:53 UTC, johnmcg23 reviewed
All reviews fixed, ready to merge

2023-12-15 15:59 UTC, johnmcg23 commented
The .gitignore file being added 4 times is out of safety of my password lmao

2024-01-11 13:29 UTC, TaylorJCrawford approved these changes

2024-01-11 13:29 UTC, TaylorJCrawford commented on FlashFeetAPI/src/main/java/org/example/api/JobRoleService.java
> +    public DatabaseConnector databaseConnector = new DatabaseConnector();
[Possible Future Improvement] - Don't need to create a new instance here. As this is being passed in via your constructor.

2024-01-11 13:29 UTC, TaylorJCrawford commented on FlashFeetAPI/src/main/java/org/example/db/DatabaseConnector.java
> +            user = props.getProperty("user");
[Possible Future Improvement]  - Similar to other PRs Environment Variables would be better here.

2024-01-11 13:29 UTC, TaylorJCrawford commented on FlashFeetAPI/src/main/java/org/example/db/JobRoleDao.java
> +    private DatabaseConnector databaseConnector = new DatabaseConnector();
[Possible Improvement] - Don't need to create a new instance here. As you are passing this via your method arguments. If you are interested the best way is to use dependency injection. https://www.freecodecamp.org/news/a-quick-intro-to-dependency-injection-what-it-is-and-when-to-use-it-7578c84fa88f/

2024-01-11 13:29 UTC, TaylorJCrawford commented on FlashFeetAPI/src/test/java/org/example/api/validator/JobsRoleValidatorTest.java
> +    void isValidJobRole_shouldReturnTrue_whenValidJobRole() {
[Possible Improvement] - I think I said this in another review. Having negative tests would be nice to see. As this is currently testing for the happy path. In addition to this boundary testing is also a very useful technique. If your interested have a look at: https://www.tutorialspoint.com/software_testing_dictionary/boundary_testing.htm

2024-01-11 13:29 UTC, TaylorJCrawford commented on FlashFeetAPI/dependency-reduced-pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
File really shouldn't be under version control. If you can, could you remove this.

2024-01-11 13:29 UTC, TaylorJCrawford commented on FlashFeetAPI/src/main/java/org/example/api/JobRoleService.java
> +    public JobRoleService(){
[Possible Future Improvement] - Don't really need this. As this provided for you by the Object Class.

2024-01-11 14:04 UTC, merged